name: link_keep_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^0.13.6
  dio: ^5.4.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_secure_storage: ^8.0.0

  # Video / Web
  youtube_player_flutter: ^9.1.3       # compatible with flutter_inappwebview >=6.0.0
  flutter_inappwebview: ^6.0.0
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Keep-Logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/default_user.png
    - assets/images/logo.png
    - assets/images/logo.jpg
    - assets/images/Keep-Logo.png
  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf
