name: link_keep_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.2.4
  webview_flutter: ^4.2.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_user.png
    - assets/images/logo.png
    - assets/images/logo.jpg
    - assets/images/Keep-Logo.png
  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf
